### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by karlzre** [imdadahad/spotify-get-current-playing-track#1]
Hi, 

Thank you for this very usefull script.
I use it to show the spotify track on a neopixel display :-)

I get sometimes this error, i just regenerate the token and it looks to fix the issue.

Any idea why the token looks to expire ?

`Traceback (most recent call last):
  File "track.py", line 59, in <module>
    main()
  File "track.py", line 42, in main
    current_track_info = get_current_track(ACCESS_TOKEN)
  File "track.py", line 21, in get_current_track
    track_id = json_resp['item']['id']
KeyError: 'item'` 

Ihere is what i get when i try the token from spotify 👍 
`{
  "error": {
    "status": 401,
    "message": "The access token expired"
  }
}`

**Comment by Mau5trakt** [comment]
The token expires 3600 secs (1 hours)

**Comment by faulty-teen** [comment]
I get the same error, My token is valid since I created it like 10 mins before using the code. I think its something with how the script handles the response to the request, I'm going to take a look and see if I can fix it
